blank_issues_enabled: true
contact_links:
  - name: Paradox Mods page / Paradox Mods 页面
    url: https://mods.paradoxplaza.com/mods/146643/Windows
    about: Subscribe to the in-game mod here. / 在这里订阅游戏内模组。
